### PR TITLE
Updated for gnome 44

### PR DESCRIPTION
**Pull request by NNakleskin**

### CODE REVIEW

**Review by lovasoa — CHANGES_REQUESTED** [review]
I just tried it, and it looks like it breaks compatibility with existing versions of gnome shell.


```
(gnome-shell:299118): Gjs-WARNING **: 21:47:09.634: JS ERROR: Extension keyboard-backlight-menu@ophir.dev: ImportError: No JS module 'quickSettings' found in search path
@/home/olojkine/.local/share/gnome-shell/extensions/keyboard-backlight-menu@ophir.dev/extension.js:24:23
_callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:460:13
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:381:27
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:640:18
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:615:19
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:646:18
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:666:14
init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:298:22
start@resource:///org/gnome/shell/ui/main.js:175:5
@resource:///org/gnome/shell/ui/init.js:6:17
```

(tested on GNOME Shell 42.9)

**Comment by ChocolateLoverRaj** [comment]
Idk if this is the case with the `lovasoa:main` branch but I tried `NNakleskin:main` out and the slider doesn't synchronize with the keyboard brightness keys on my laptop.

**Comment by ChocolateLoverRaj** [comment]
Also I'm not sure if this is PR specific but the keyboard brightness slider is all the way at the bottom instead of next to the screen brightness slider. 
image

**Comment by ChocolateLoverRaj** [comment]
Also I'm not sure if this is PR specific but the keyboard brightness slider is all the way at the bottom instead of next to the screen brightness slider. 
image

**Comment by ChocolateLoverRaj** [comment]
Doesn't GNOME have this slider built-in in GNOME 45?

**Comment by lovasoa** [comment]
No, at least I don't have it on my vanilla ubuntu 24.04.

**Comment by ChocolateLoverRaj** [comment]
https://www.omglinux.com/gnome-adds-keyboard-backlight-control/

Interesting because the article talks about using this very extension before

**Comment by lovasoa** [comment]
My bad; actually it's there, but it's not a slider: 

image

**Comment by ChocolateLoverRaj** [comment]
Does your keyboard have more than 3 levels of light brightness?

Image

**Comment by lovasoa** [comment]
no

**Comment by ChocolateLoverRaj** [comment]
How useful is this GNOME extension in GNOME 45? Is it still worth it to maintain?

**Comment by lovasoa** [comment]
It's mostly useless now, I won't maintain it.

**Pull request merged**
